### ISSUE TITLE
How to restore soft deleted record

### ISSUE THREAD

**Issue by anhtuank7c** [PGBI/cakephp3-soft-delete#12]
Dear owner.
Please provide function restore to restore soft deleted record.
I'm sorry if i miss something.

**Comment by PGBI** [comment]
I've added a restore() method on version 1.3.0 of the plugin.

**Comment by anhtuank7c** [comment]
Thanks.
But seem like references records does not restore too.
Ex: Groups 1:n Users
When soft delete one record in Groups table, n records in Users table related to groups will soft deleted too.
When restore group record, i think n users will restore too, instead of restore one by one user record.
I did not test your code, but look at code, i see you just restore one by one.
