### ISSUE TITLE
deleteAll doesn't delete associations

### ISSUE THREAD

**Issue by shembelcut** [PGBI/cakephp3-soft-delete#14]
The `deleteAll()` does not delete the associations however it is all fine with a single row deleting as we have [`cascadeDelete()`] (https://github.com/PGBI/cakephp3-soft-delete/blob/master/src/Model/Table/SoftDeleteTrait.php#L79)  in `_processDelete()`, but not in [`deleteAll()`] (https://github.com/PGBI/cakephp3-soft-delete/blob/master/src/Model/Table/SoftDeleteTrait.php#L108).

**Comment by steefaan** [comment]
+1

**Comment by PGBI** [comment]
This is the normal cakephp behavior, it is not linked with the soft delete plugin. `deleteAll` (whether it is soft or hard deletion) does not cascade to associations:

See http://api.cakephp.org/3.0/class-Cake.Datasource.RepositoryInterface.html#_deleteAll
> This method will not execute on associations' cascade attribute. You should use database foreign keys + ON CASCADE rules if you need cascading deletes combined with this method.
