### ISSUE TITLE
Non-configured delete field can delete all records

### ISSUE THREAD

**Issue by davidyell** [PGBI/cakephp3-soft-delete#5]
**Setup**
My setup is that I have `boolean deleted` and `datetime deleted_date`.

**What I did**
Added the Trait to my table and called `hardDeleteAll()`.

**What happened**
All records in my table were deleted.

**What I expected to happen**
I would expect no records to be deleted, or an exception to be thrown if the default field doesn't exist in the Tables schema. Perhaps something like `$entity->has($field)`

**Comment by davidyell** [comment]
If I get some time today, I'll see if I can submit a PR for this.

**Comment by PGBI** [comment]
Indeed, that's an annoying behavior... Thanks for reporting it!
I like the idea of throwing an exception. I think it should be extended to all method and not only the `hardDeleteAll()` one. Perhaps you could check if the soft delete field exists in `getSoftDeleteField()`.

**Comment by davidyell** [comment]
Yes, that's a good idea.

**Comment by PGBI** [comment]
@davidyell are you still planning on submitting a PR, or do you want me to work on this?

**Comment by davidyell** [comment]
Oh, so sorry I totally forgot. If you don't mind taking it on that would be
great. Thanks!

**Comment by PGBI** [comment]
No pb, i'll do it.
